apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "flask-mongodb.configmapName" . }}
  namespace: {{ include "flask-mongodb.namespace" . }}
  labels:
    {{- include "flask-mongodb.labels" . | nindent 4 }}

data:
  MONGO_HOST: {{ include "flask-mongodb.mongodb.serviceName" . | quote }}
  MONGO_PORT: {{ .Values.mongodb.service.port | quote }}
  MONGO_DB_NAME: {{ .Values.config.mongoDbName | quote }}
  FLASK_ENV: {{ .Values.flask.env.FLASK_ENV | quote }}
  FLASK_DEBUG: {{ .Values.flask.env.FLASK_DEBUG | quote }}
