apiVersion: v1
kind: Service

metadata:
  name: {{ include "flask-mongodb.mongodb.serviceName" . }}
  namespace: {{ include "flask-mongodb.namespace" . }}
  labels:
    {{- include "flask-mongodb.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb

spec:
  type: {{ .Values.mongodb.service.type }}

  selector:
    {{- include "flask-mongodb.mongodb.selectorLabels" . | nindent 4 }}

  ports:
    - name: mongodb
      protocol: TCP
      port: {{ .Values.mongodb.service.port }}
      targetPort: {{ .Values.mongodb.service.port }}
