{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "flask-mongodb.namespace" . }}
  labels:
    {{- include "flask-mongodb.labels" . | nindent 4 }}
    environment: production
{{- end }}
