apiVersion: v1
kind: Secret

metadata:
  name: {{ include "flask-mongodb.secretName" . }}
  namespace: {{ include "flask-mongodb.namespace" . }}
  labels:
    {{- include "flask-mongodb.labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}

type: Opaque

data:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.secrets.mongoRootUsername | b64enc | quote }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.secrets.mongoRootPassword | b64enc | quote }}
  FLASK_SECRET_KEY: {{ .Values.secrets.flaskSecretKey | b64enc | quote }}
