apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: mongodb-pvc
  namespace: flask-mongodb
  labels:
    app: mongodb
    app.kubernetes.io/part-of: flask-mongodb

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 1Gi

  storageClassName: standard
