apiVersion: v1
kind: ConfigMap

metadata:
  name: flask-mongodb-config
  namespace: flask-mongodb
  labels:
    app.kubernetes.io/part-of: flask-mongodb

data:
  MONGO_HOST: "mongodb-service"
  MONGO_PORT: "27017"
  MONGO_DB_NAME: "TaskManager"
  FLASK_ENV: "production"
  FLASK_DEBUG: "0"
